"""Built-in catalog of the implementations already present in this project."""

from __future__ import annotations

from src.workflow.contracts import ActivationMode, NodeImplementationSpec, NodePort
from src.workflow.registry import WorkflowNodeRegistry, register_many


def _ports(input_type: str, output_type: str) -> tuple[tuple[NodePort, ...], tuple[NodePort, ...]]:
    return (
        (NodePort("request", input_type, description="Normalized stage request"),),
        (NodePort("result", output_type, description="Normalized stage result"),),
    )


def _spec(
    stage: str,
    implementation_id: str,
    label: str,
    description: str,
    entrypoint: str,
    activation_mode: ActivationMode,
    input_type: str,
    output_type: str,
    *,
    default: bool = False,
    notes: tuple[str, ...] = (),
) -> NodeImplementationSpec:
    inputs, outputs = _ports(input_type, output_type)
    return NodeImplementationSpec(
        stage=stage,
        implementation_id=implementation_id,
        label=label,
        description=description,
        entrypoint=entrypoint,
        activation_mode=activation_mode,
        inputs=inputs,
        outputs=outputs,
        default=default,
        notes=notes,
    )


BUILTIN_IMPLEMENTATIONS = (
    _spec(
        "trend_collection",
        "douyin_authorized_web",
        "抖音授权页面采集",
        "采集当前授权范围内可见的关键词、排序和标签族样本。",
        "src.trend_intelligence.providers.douyin_web:DouyinWebTrendProvider",
        ActivationMode.HOT_SWITCH,
        "trend_collection_request/v1",
        "trend_observations/v2",
        default=True,
    ),
    _spec(
        "trend_collection",
        "manual_import",
        "人工数据导入",
        "从经过确认的本地文件导入样本；当前登记接口，页面适配待完成。",
        "src.trend_intelligence.providers.manual_import",
        ActivationMode.PROFILE_ONLY,
        "trend_collection_request/v1",
        "trend_observations/v2",
    ),
    _spec(
        "media_acquisition",
        "metadata_only",
        "页面元数据",
        "只保留视频 ID、标题、作者、标签、排序和页面展示指标，不下载视频。",
        "src.trend_intelligence.providers.douyin_web:DouyinWebTrendProvider",
        ActivationMode.HOT_SWITCH,
        "media_acquisition_request/v1",
        "media_artifacts/v1",
        default=True,
    ),
    _spec(
        "media_acquisition",
        "authorized_local_media",
        "授权本地视频",
        "对已取得处理权限并已落地的本地视频建立分析产物映射。",
        "src.trend_intelligence.content_analysis.toolchain:LocalContentToolchain",
        ActivationMode.PROFILE_ONLY,
        "media_acquisition_request/v1",
        "media_artifacts/v1",
    ),
    _spec(
        "content_analysis",
        "metadata_heuristic",
        "轻量元数据分析",
        "根据标题、标签和页面文本识别主题、钩子、展示方式与账号相关度。",
        "src.trend_intelligence.content_analysis.metadata:MetadataContentAnalysisProvider",
        ActivationMode.HOT_SWITCH,
        "video_content_analysis_request/v1",
        "video_content_analysis/v1",
        default=True,
    ),
    _spec(
        "content_analysis",
        "local_qwen_paraformer",
        "本地 Qwen + Paraformer",
        "对授权本地媒体执行视觉理解、语音识别和分段分析。",
        "src.trend_intelligence.content_analysis.local:LocalQwenParaformerProvider",
        ActivationMode.PROFILE_ONLY,
        "video_content_analysis_request/v1",
        "video_content_analysis/v1",
    ),
    _spec(
        "opportunity_ranking",
        "explainable_rules",
        "可解释机会评分",
        "综合流量、时间、账号相关度、内容证据、反馈和风险生成机会排行。",
        "src.trend_intelligence.opportunity.scoring:ContentOpportunityScorer",
        ActivationMode.HOT_SWITCH,
        "content_opportunity_request/v1",
        "content_opportunities/v1",
        default=True,
    ),
    _spec(
        "llm",
        "openai_compatible",
        "OpenAI 兼容接口",
        "脚本、对话、Agent 等共用的远程兼容接口。",
        "src.shared.llm_providers.openai_compatible_provider:OpenAICompatibleProvider",
        ActivationMode.EXTERNAL_CONFIG,
        "llm_request/v1",
        "llm_response/v1",
        default=True,
    ),
    _spec(
        "llm",
        "ollama",
        "Ollama 本地模型",
        "通过本地 Ollama 服务完成文本生成。",
        "src.shared.llm_providers.ollama_provider:OllamaProvider",
        ActivationMode.EXTERNAL_CONFIG,
        "llm_request/v1",
        "llm_response/v1",
    ),
    _spec(
        "llm",
        "mock",
        "Mock 测试模型",
        "离线测试和契约验证使用，不用于生产内容。",
        "src.shared.llm_providers.mock_provider:MockProvider",
        ActivationMode.EXTERNAL_CONFIG,
        "llm_request/v1",
        "llm_response/v1",
    ),
    _spec(
        "tts",
        "edge",
        "Edge-TTS",
        "联网语音合成，当前稳定兜底。",
        "src.content_factory.tts_providers.edge_tts_provider:EdgeTTSProvider",
        ActivationMode.HOT_SWITCH,
        "tts_request/v1",
        "audio_artifact/v1",
        default=True,
    ),
    _spec(
        "tts",
        "gpt_sovits",
        "GPT-SoVITS",
        "本地克隆音色，依赖独立 Python、权重和参考音频。",
        "src.content_factory.tts_providers.gpt_sovits_provider:GPTSoVITSProvider",
        ActivationMode.HOT_SWITCH,
        "tts_request/v1",
        "audio_artifact/v1",
    ),
    _spec(
        "background",
        "disabled_pending_redesign",
        "背景生成已重置",
        "旧背景生成与本地兜底不再作为生产节点，等待 Video Pipeline V2 重新选型。",
        "src.workflow.disabled:reject_execution",
        ActivationMode.HOT_SWITCH,
        "background_request/v1",
        "image_artifact/v1",
        default=True,
        notes=("comfyui_flux、local_fallback 已退出当前生产工作流。",),
    ),
    _spec(
        "video_pipeline",
        "disabled_pending_redesign",
        "视频生成已重置",
        "旧视频生成路线质量未达标，当前不提供生产成片能力。",
        "src.workflow.disabled:reject_execution",
        ActivationMode.HOT_SWITCH,
        "content_video_request/v1",
        "video_artifact/v1",
        default=True,
        notes=(
            "presenter_anime、dual_framepack_active、single_template 已于 2026-09-04 退役。",
            "历史代码仅供归档追溯，不得用于生产发布。",
        ),
    ),
    _spec(
        "portrait_animation",
        "disabled_pending_redesign",
        "人物驱动已重置",
        "旧人物驱动实现不再作为生产节点，等待 Video Pipeline V2 重新选型。",
        "src.workflow.disabled:reject_execution",
        ActivationMode.HOT_SWITCH,
        "portrait_animation_request/v1",
        "video_artifact/v1",
        default=True,
        notes=("sonic、sadtalker、liveportrait、musetalk 已退出当前生产工作流。",),
    ),
    _spec(
        "video_generation",
        "disabled_pending_redesign",
        "镜头生成已重置",
        "旧图生视频实现不再作为生产节点，等待逐镜头质量验收后重新接入。",
        "src.workflow.disabled:reject_execution",
        ActivationMode.HOT_SWITCH,
        "video_generation_request/v1",
        "video_artifact/v1",
        default=True,
        notes=(
            "ltx_i2v、wan_animate_move、framepack、seedance_dreamina、seedance_byteplus 已退出当前生产工作流。",
        ),
    ),
    _spec(
        "frame_interpolation",
        "disabled_pending_redesign",
        "插帧节点已重置",
        "旧插帧实现不再作为生产节点，等待 Video Pipeline V2 重新验收。",
        "src.workflow.disabled:reject_execution",
        ActivationMode.HOT_SWITCH,
        "frame_interpolation_request/v1",
        "video_artifact/v1",
        default=True,
        notes=("rife、ffmpeg_minterpolate 已退出当前生产工作流。",),
    ),
    _spec(
        "composition",
        "disabled_pending_redesign",
        "成片合成已重置",
        "旧合成器不再作为生产节点，等待 FinalVideo/v2 合同实现。",
        "src.workflow.disabled:reject_execution",
        ActivationMode.HOT_SWITCH,
        "composition_request/v1",
        "video_artifact/v1",
        default=True,
        notes=("旧 FFmpeg 合成路线仅保留代码追溯，不得从生产工作流调用。",),
    ),
    _spec(
        "publishing",
        "douyin_playwright",
        "抖音 Playwright 发布",
        "使用持久登录态上传并登记发布结果。",
        "src.platform_adapter.douyin_adapter:DouyinAdapter",
        ActivationMode.HOT_SWITCH,
        "publish_request/v1",
        "publish_receipt/v1",
        default=True,
    ),
)


def build_default_registry() -> WorkflowNodeRegistry:
    return register_many(WorkflowNodeRegistry(), BUILTIN_IMPLEMENTATIONS)
