"""Built-in catalog of the implementations already present in this project."""

from __future__ import annotations

from src.workflow.contracts import ActivationMode, NodeImplementationSpec, NodePort
from src.workflow.registry import WorkflowNodeRegistry, register_many


def _ports(input_type: str, output_type: str) -> tuple[tuple[NodePort, ...], tuple[NodePort, ...]]:
    return (
        (NodePort("request", input_type, description="Normalized stage request"),),
        (NodePort("result", output_type, description="Normalized stage result"),),
    )


def _spec(
    stage: str,
    implementation_id: str,
    label: str,
    description: str,
    entrypoint: str,
    activation_mode: ActivationMode,
    input_type: str,
    output_type: str,
    *,
    default: bool = False,
    notes: tuple[str, ...] = (),
) -> NodeImplementationSpec:
    inputs, outputs = _ports(input_type, output_type)
    return NodeImplementationSpec(
        stage=stage,
        implementation_id=implementation_id,
        label=label,
        description=description,
        entrypoint=entrypoint,
        activation_mode=activation_mode,
        inputs=inputs,
        outputs=outputs,
        default=default,
        notes=notes,
    )


BUILTIN_IMPLEMENTATIONS = (
    _spec(
        "llm",
        "openai_compatible",
        "OpenAI 兼容接口",
        "脚本、对话、Agent 等共用的远程兼容接口。",
        "src.shared.llm_providers.openai_compatible_provider:OpenAICompatibleProvider",
        ActivationMode.EXTERNAL_CONFIG,
        "llm_request/v1",
        "llm_response/v1",
        default=True,
    ),
    _spec(
        "llm",
        "ollama",
        "Ollama 本地模型",
        "通过本地 Ollama 服务完成文本生成。",
        "src.shared.llm_providers.ollama_provider:OllamaProvider",
        ActivationMode.EXTERNAL_CONFIG,
        "llm_request/v1",
        "llm_response/v1",
    ),
    _spec(
        "llm",
        "mock",
        "Mock 测试模型",
        "离线测试和契约验证使用，不用于生产内容。",
        "src.shared.llm_providers.mock_provider:MockProvider",
        ActivationMode.EXTERNAL_CONFIG,
        "llm_request/v1",
        "llm_response/v1",
    ),
    _spec(
        "tts",
        "edge",
        "Edge-TTS",
        "联网语音合成，当前稳定兜底。",
        "src.content_factory.tts_providers.edge_tts_provider:EdgeTTSProvider",
        ActivationMode.HOT_SWITCH,
        "tts_request/v1",
        "audio_artifact/v1",
        default=True,
    ),
    _spec(
        "tts",
        "gpt_sovits",
        "GPT-SoVITS",
        "本地克隆音色，依赖独立 Python、权重和参考音频。",
        "src.content_factory.tts_providers.gpt_sovits_provider:GPTSoVITSProvider",
        ActivationMode.HOT_SWITCH,
        "tts_request/v1",
        "audio_artifact/v1",
    ),
    _spec(
        "background",
        "comfyui_flux",
        "ComfyUI / Flux 背景",
        "按场景生成动漫背景，失败时由现有 Presenter 流程兜底。",
        "src.content_factory.presenter.background_resolver:BackgroundResolver",
        ActivationMode.HOT_SWITCH,
        "background_request/v1",
        "image_artifact/v1",
        default=True,
    ),
    _spec(
        "background",
        "local_fallback",
        "本地兜底背景",
        "不启动 ComfyUI，使用本地规则生成的快速背景。",
        "src.content_factory.presenter.background_resolver:BackgroundResolver",
        ActivationMode.HOT_SWITCH,
        "background_request/v1",
        "image_artifact/v1",
    ),
    _spec(
        "video_pipeline",
        "presenter_anime",
        "动漫数字人主讲",
        "脚本、配音、背景、角色层、字幕的一体化 Presenter 流程。",
        "src.services.auto_publish_service:AutoPublishService",
        ActivationMode.HOT_SWITCH,
        "content_video_request/v1",
        "video_artifact/v1",
        default=True,
    ),
    _spec(
        "video_pipeline",
        "dual_framepack_active",
        "双角色主动说话",
        "复用 FramePack 角色序列并按说话时间轴高亮。",
        "src.services.auto_publish_service:AutoPublishService",
        ActivationMode.HOT_SWITCH,
        "content_video_request/v1",
        "video_artifact/v1",
    ),
    _spec(
        "video_pipeline",
        "single_template",
        "单人口播模板",
        "旧模板视频循环与配音合成入口。",
        "src.services.auto_publish_service:AutoPublishService",
        ActivationMode.HOT_SWITCH,
        "content_video_request/v1",
        "video_artifact/v1",
    ),
    _spec(
        "portrait_animation",
        "sonic",
        "Sonic",
        "动漫音频驱动头像路线，必须经过视觉审核。",
        "ComfyUI_Sonic workflow / existing Sonic assets",
        ActivationMode.PROFILE_ONLY,
        "portrait_animation_request/v1",
        "video_artifact/v1",
        default=True,
    ),
    _spec(
        "portrait_animation",
        "sadtalker",
        "SadTalker",
        "真人或近真人方形说话头像，已有全画面 provider 脚本。",
        "scripts.sadtalker_fullframe_provider:HybridLiveActionV61Provider",
        ActivationMode.PROFILE_ONLY,
        "portrait_animation_request/v1",
        "video_artifact/v1",
    ),
    _spec(
        "portrait_animation",
        "liveportrait",
        "LivePortrait",
        "表情和微动作稳定，精确口型不是默认强项。",
        "ComfyUI-LivePortraitKJ / external LivePortrait",
        ActivationMode.PROFILE_ONLY,
        "portrait_animation_request/v1",
        "video_artifact/v1",
    ),
    _spec(
        "portrait_animation",
        "musetalk",
        "MuseTalk",
        "固定音频口型路线，现有脚本以批处理方式接入。",
        "scripts.run_musetalk_fixed_audio:main",
        ActivationMode.PROFILE_ONLY,
        "portrait_animation_request/v1",
        "video_artifact/v1",
    ),
    _spec(
        "video_generation",
        "ltx_i2v",
        "LTX I2V",
        "自由镜头和场景动作的本地 ComfyUI 路线。",
        "scripts.comfy_ltx_antifraud_batch / LTX ComfyUI workflows",
        ActivationMode.PROFILE_ONLY,
        "video_generation_request/v1",
        "video_artifact/v1",
        default=True,
    ),
    _spec(
        "video_generation",
        "wan_animate_move",
        "WAN Animate Move",
        "驱动视频、人物遮罩和静态背景锁定路线。",
        "assets.workflows.wan22_i2v_api / ComfyUI WanVideoWrapper",
        ActivationMode.PROFILE_ONLY,
        "video_generation_request/v1",
        "video_artifact/v1",
    ),
    _spec(
        "video_generation",
        "framepack",
        "FramePack",
        "本地 I2V 微动作路线，目前由项目脚本调用外部工程。",
        "scripts.run_task1_story_v63_framepack_batch:main",
        ActivationMode.PROFILE_ONLY,
        "video_generation_request/v1",
        "video_artifact/v1",
    ),
    _spec(
        "video_generation",
        "seedance_dreamina",
        "Seedance / 即梦 CLI",
        "通过即梦官方 CLI 提交云端 Seedance 任务。",
        "src.content_factory.dreamina_cli:DreaminaCLIClient",
        ActivationMode.PROFILE_ONLY,
        "video_generation_request/v1",
        "video_artifact/v1",
    ),
    _spec(
        "video_generation",
        "seedance_byteplus",
        "Seedance / BytePlus API",
        "通过 BytePlus API 提交 Seedance 任务。",
        "src.content_factory.seedance_client:SeedanceClient",
        ActivationMode.PROFILE_ONLY,
        "video_generation_request/v1",
        "video_artifact/v1",
    ),
    _spec(
        "frame_interpolation",
        "rife",
        "RIFE",
        "神经网络插帧，需在结构和光照通过后执行。",
        "scripts.comfy_rife_batch:main",
        ActivationMode.PROFILE_ONLY,
        "frame_interpolation_request/v1",
        "video_artifact/v1",
        default=True,
    ),
    _spec(
        "frame_interpolation",
        "ffmpeg_minterpolate",
        "FFmpeg minterpolate",
        "轻量插帧兜底，已有 smoothness gate 约束。",
        "src.content_factory.video_smoothness:run_video_smoothness",
        ActivationMode.PROFILE_ONLY,
        "frame_interpolation_request/v1",
        "video_artifact/v1",
    ),
    _spec(
        "composition",
        "ffmpeg",
        "FFmpeg 合成器",
        "单人、双人、时间线、字幕和音频合成主入口。",
        "src.content_factory.video_composer",
        ActivationMode.HOT_SWITCH,
        "composition_request/v1",
        "video_artifact/v1",
        default=True,
    ),
    _spec(
        "publishing",
        "douyin_playwright",
        "抖音 Playwright 发布",
        "使用持久登录态上传并登记发布结果。",
        "src.platform_adapter.douyin_adapter:DouyinAdapter",
        ActivationMode.HOT_SWITCH,
        "publish_request/v1",
        "publish_receipt/v1",
        default=True,
    ),
)


def build_default_registry() -> WorkflowNodeRegistry:
    return register_many(WorkflowNodeRegistry(), BUILTIN_IMPLEMENTATIONS)
